### ISSUE TITLE
视频加字幕怎么实现呢

### ISSUE THREAD

**Issue by newbiefly** [mengzhidaren/FFmpegCmdSdk#4]
一直报Fontconfig error: Cannot load default config file，应该是找不到字体，我有字体，在SD卡中，要怎么设置才能使用我SD卡里面的ttf文件？

**Comment by mengzhidaren** [comment]
官方app里有设置字体的功能 ，不过好像是一个指定的数组里选择， 外部的字体文件我没试过，  你查下源代码里的api吧

**Comment by mengzhidaren** [comment]
不知道
