### ISSUE TITLE
arm64-v8a Support

### ISSUE THREAD

**Issue by adapana** [mengzhidaren/FFmpegCmdSdk#6]
@mengzhidaren 
Can you provide arm64-v8a version of .so files?
From August 1, Google will not be supporting an app that only provides 32-bit native libraries.
So if possible then please update the library.

Thanks.

**Comment by mengzhidaren** [comment]
I'll update it when I have time.

**Comment by mengzhidaren** [comment]
Updated

**Comment by adapana** [comment]
Thanks
